language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm install -g vuepress
  - npm install --save
  - cp ./CodeSwitcher.vue node_modules/vuepress-plugin-code-switcher/components/
  - vuepress build docs
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master
